Find and use default mime.types file
It turns out nginx isn't very good at serving files with the correct Content-Type header without MIME type mappings.  Find and include the set installed with nginx if at all possible, or abort if they can't be found.

diff --git a/bin/nginx-dev b/bin/nginx-dev
--- a/bin/nginx-dev
+++ b/bin/nginx-dev
@@ -21,8 +21,8 @@
 
 set -e
 
-# Get top level directory of git repository.  It's the parent
-# directory of the directory containing this script.
+# Get top level directory of the CodeCity git repository.  It's the
+# parent directory of the directory containing this script.
 repo="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. >/dev/null 2>&1 && pwd)"
 
 # Create var directory if required
@@ -33,6 +33,20 @@ if [[ ! -d "$repo/var" ]] ; then
   fi
 
   mkdir "$repo/var"
+fi
+
+# Find location where the nginx installation keeps its config files.
+# We only want the mime.types file.
+for dir in "$(brew --prefix)/etc" /usr/local/etc /etc; do
+  if [[ -d "$dir" && -f "$dir/nginx/mime.types" ]] ; then
+    mimetypes="$dir/nginx/mime.types"
+    break;
+  fi
+done
+
+if [[ -z "$mimetypes" ]] ; then
+  echo "$0: can't find mime.types file." 1>&2
+  exit 1;
 fi
 
 cat >"$repo/var/nginx-dev.conf" <<EOF
@@ -50,6 +64,7 @@ events {
 
 http {
   access_log off;
+  include $mimetypes;
   default_type application/octet-stream;
 
   # Set temp paths to be in $repo/var:
